### ISSUE TITLE
How to run commands?

### ISSUE THREAD

**Issue by Crell** [tpluscode/action-setup-lando#7]
I'm giving this Action a whirl on a Laravel project with Lando.  I can get it to set up correctly, it seems, but I cannot reliably get commands to run inside the app container.  That's necessary for doing things like running tests.  (Without that, there's not much reason to run Lando in an action.)

I'm trying to do this:

```yaml

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: setup-docker
              uses: docker-practice/actions-setup-docker@1.0.4
            - uses: tpluscode/action-setup-lando@master
              with:
                  version: v3.6.5
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - run: lando xdebug-on
            - run: lando ssh --command composer install
            - run: lando ssh --command php artisan migrate
            - run: lando ssh --command php artisan db:seed
            - run: echo "::error try to fail"
            - run: lando ssh --command echo "::error try to fail"
            - run: lando ssh --command vendor/bin/phpunit --coverage-clover clover.xml || echo "::error Tests failed."
```

Unfortunately, every one of those `run` statements passes with no output, except for the non-lando echo, which just prints the message but still succeeds.  I would expect either that or the line after it to fail, or for the phpunit command to fail since I deliberately introduced a failing test.

What am I missing here?  The docs so far don't seem to say how to do anything beyond boot it up.
